[project]
name = 'tixi_verse'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.event-refund]
path = 'contracts/event-refund.clar'
clarity_version = 2
epoch = 2.5

[contracts.event-registration]
path = 'contracts/event-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.event-ticketing]
path = 'contracts/event-ticketing.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
